title: Ebsid's Homepage
page-top-title: Ebsid
top-section-bg-text: |
  Event-based swarm intelligent decision
  "事件驱动群体智能决策"
home-subtitle: Ebsid课题组&ensp;|&ensp;群智决策课题组
copyright-text: '&copy; Ebsid 2023-2025. All Rights Reserved.'
